@startuml
!theme plain
left to right direction

actor Student as s

rectangle "Classhub" {
    rectangle "Source Management" {
        usecase "Add New Source" as ANS
        usecase "Add Repo" as AREPO
        usecase "Add Drive (public)" as ADRIVE
        usecase "Add Classroom" as ACLASSROOM

        usecase "Sync Source" as SS
        usecase "Sync All Sources" as SAS

        usecase "Share Sources" as SSS
    }

    rectangle "Local Document Management" {
        usecase "Navigate Documents" as ND
        usecase "Open Document" as OD
        usecase "Add new Document to Local Document Space" as AD
    }

    usecase "Google Auth" as AUTH
}

s --> ANS
s --> SS
s --> SAS
s --> SSS
s --> ND
s --> OD
s --> AD

AREPO      .up.> ANS  : <<extend>>
ADRIVE     .up.> ANS  : <<extend>>
ACLASSROOM .up.> ANS  : <<extend>>
ACLASSROOM ..> AUTH : <<include>>
@enduml

