@startuml
!theme plain
left to right direction

actor Student as s

rectangle "Classhub" {
    rectangle "Source Management" {
        usecase "Add New Source" as ANS
        usecase "Add Repo" as AREPO
        usecase "Add Drive (public)" as ADRIVE
        usecase "Add Classroom" as ACLASSROOM

        usecase "Sync Source" as SS
        usecase "Sync All Sources" as SAS
        usecase "view sync status" as VSS

        usecase "Share Sources" as SSS
        note right of SSS : share as a URI containing a string of all sources URLs\nopens directly in the app
    }

    rectangle "File Management" {
        usecase "Create local folders and Documents" as CFAD
        usecase "Browse & Open Documents" as BND
        usecase "Delete File / Folder" as DFF
    }

    usecase "Google Auth" as AUTH
}

s --> ANS
s --> SS
s --> SAS
s --> VSS
s --> SSS
s --> BND
s --> CFAD
s --> DFF

SAS .> SS : <<include>>

AREPO      .up.> ANS  : <<extend>>
ADRIVE     .up.> ANS  : <<extend>>
ACLASSROOM .up.> ANS  : <<extend>>
ACLASSROOM ..> AUTH : <<include>>
@enduml
