@startuml
left to right direction

actor Student as s

rectangle "Classhub" {
    usecase "add new source" as ANS

    usecase "sync source" as SS
    usecase "sync all sources" as SAS
    usecase "share sources" as SSS
    usecase "navigate between sources" as NBS
    usecase "add document to local space" as AD
    usecase "open documents" as OD

    usecase "add repo as a source" as AREPO
    usecase "add drive(public) as a source" as ADRIVE
    usecase "add classroom as a source" as ACLASSROOM

    usecase "google auth/login" as AUTH
}

s ---> ANS

s --> SS
s --> SAS
s --> NBS
s --> AD
s --> OD
s --> SSS

AREPO ..> ANS  : <<extend>>
ADRIVE ..> ANS  : <<extend>>
ACLASSROOM ..> ANS  : <<extend>>

ACLASSROOM ..> AUTH : <<include>>
@enduml
